name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reusable Workflow
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run script to trigger reusable workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --data '{"ref":"main","inputs":{"json-file-path":"path/to/your/file.json"}}' \
            "https://api.github.com/repos/krishaapsingh/reusable-workflow-repo/actions/workflows/reusable-workflow.yml/dispatches"
