name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository Token
        id: get_token
        run: echo "::set-output name=token::$(echo -n ${{ secrets.PAT }} | base64)"
      
      - name: Trigger Reusable Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: apsinghuiet/doc-reusable-workflow
          event-type: trigger-reusable-workflow
          client-payload: '{"ref": "main", "inputs": {"message": "Hello from the caller workflow!", "json_file_path": "./pkpbundle.json"}}'
