name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository Token
        id: get_token
        run: echo "::set-output name=token::$(echo -n ${{ secrets.PAT }} | base64)"
      
      - name: Trigger Reusable Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/apsinghuiet/doc-reusable-workflow/actions/workflows/reusable-workflow.yml/dispatches \
            -d '{"ref": "main", "inputs": {"message": "Hello from the caller workflow!"}'
