
# doc-publisher-workflow/.github/workflows/update-pkp-bundle.yml

name: Update JSON

on:
  push:
    paths:
      - 'pkpbundle.json'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run script to trigger reusable workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --data '{"ref":"main","inputs":{"json-file-path":"pkpbundle.json"}}' \
            "https://api.github.com/repos/anandu-m-s/githubAction-demo/actions/workflows/read-json.yaml/dispatches"
