name: Caller Workflow

on:
  workflow_run:
    workflows: ["reusable_workflow"]  # Specify the name of the reusable workflow here
    types:
      - completed

jobs:
  trigger-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reusable Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: apsinghuiet/doc-reusable-workflow  # Specify the repository where the reusable workflow is located
          event-type: trigger-reusable-workflow
          client-payload: '{"workflow": "reusable-workflow", "json-file-path": "pkpbundle.json"}'
