name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reusable Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: apsinghuiet/doc-reusable-workflow
          event-type: trigger-reusable-workflow
          client-payload: '{"message": "Hello from the caller workflow!"}'
